### training에 필요한 세가지 

1. Model : hypothesis
2. Cost function
3. Gradient descent algorithm : 최적화 알고리즘

## Multivariable Linear Regression

하나의 input이 아니라 여러 개의 inputs을 넣을 때, 즉 mluti-variable/feature일 때 y_target 값을 예측한다.

input이 3개 일때 다음과 같이 선형모형(Model or Hypothesis)을 쓸수 있다.

$$ H(x_1, x_2, x_3) = w_1x_1 + w_2x_2 + w_3x_3 + b$$


In [2]:
import tensorflow as tf
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152, 185, 180, 196, 142]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

# Variables
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

# model
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# minimize 
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 20 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:", hy_val)

0 Cost: 9654.002 
Prediction: [64.38505 80.21223 78.03302 80.42699 65.45741]
20 Cost: 4.608468 
Prediction: [151.5526  184.9665  181.25667 192.83586 145.35411]
40 Cost: 4.5926948 
Prediction: [151.561   184.9621  181.25974 192.8402  145.34634]
60 Cost: 4.5771384 
Prediction: [151.56856 184.95676 181.26184 192.8434  145.33786]
80 Cost: 4.5616884 
Prediction: [151.57608 184.95142 181.26389 192.84662 145.32944]
100 Cost: 4.546379 
Prediction: [151.58354 184.94612 181.26598 192.84984 145.32104]
120 Cost: 4.5311913 
Prediction: [151.59096 184.94086 181.268   192.85303 145.31268]
140 Cost: 4.5161476 
Prediction: [151.59834 184.93561 181.27002 192.8562  145.30437]
160 Cost: 4.501248 
Prediction: [151.60568 184.93044 181.2721  192.8594  145.29611]
180 Cost: 4.4864416 
Prediction: [151.61296 184.92525 181.2741  192.86256 145.28786]
200 Cost: 4.471822 
Prediction: [151.62022 184.92012 181.2761  192.86572 145.2797 ]
220 Cost: 4.457287 
Prediction: [151.62741 184.91501 181.27808 192.86887 145.2715

In [3]:
y_data

[152, 185, 180, 196, 142]

예측 결과, 실제 y_data 값과 거의 유사한 값으로 수렴되었다.

### matrix를 이용해 다시 구현

In [6]:
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]

x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90], [96., 98., 100.], [73., 66., 70]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])  # 여기에서는 None=5 데이터 수
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# model
hypothesis = tf.matmul(X, W) + b

# cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize and train
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    
    if step % 20 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:", hy_val)

0 Cost: 245451.55 
Prediction: [[-289.36374]
 [-342.9916 ]
 [-340.4735 ]
 [-369.8221 ]
 [-261.2781 ]]
20 Cost: 0.9109496 
Prediction: [[150.23128]
 [185.36198]
 [180.12592]
 [197.09642]
 [141.7219 ]]
40 Cost: 0.90845174 
Prediction: [[150.2389 ]
 [185.36438]
 [180.13188]
 [197.10178]
 [141.72299]]
60 Cost: 0.90596163 
Prediction: [[150.24254]
 [185.36197]
 [180.13307]
 [197.10193]
 [141.72043]]
80 Cost: 0.90351087 
Prediction: [[150.24614]
 [185.35957]
 [180.13426]
 [197.1021 ]
 [141.71788]]
100 Cost: 0.9010662 
Prediction: [[150.24973]
 [185.35718]
 [180.13545]
 [197.10223]
 [141.71535]]
120 Cost: 0.8986536 
Prediction: [[150.2533 ]
 [185.35483]
 [180.13663]
 [197.10239]
 [141.71283]]
140 Cost: 0.89626056 
Prediction: [[150.25684]
 [185.35245]
 [180.13782]
 [197.10252]
 [141.71033]]
160 Cost: 0.8938885 
Prediction: [[150.26038]
 [185.35011]
 [180.13899]
 [197.10268]
 [141.70784]]
180 Cost: 0.8915469 
Prediction: [[150.26387]
 [185.34776]
 [180.14015]
 [197.10281]
 [141.70537]]
200 Cos

1700 Cost: 0.7587969 
Prediction: [[150.48619]
 [185.2007 ]
 [180.21503]
 [197.10431]
 [141.55688]]
1720 Cost: 0.75751686 
Prediction: [[150.4886 ]
 [185.19911]
 [180.21585]
 [197.10423]
 [141.55537]]
1740 Cost: 0.7562331 
Prediction: [[150.49101]
 [185.19754]
 [180.21667]
 [197.10414]
 [141.55388]]
1760 Cost: 0.7549708 
Prediction: [[150.4934 ]
 [185.19597]
 [180.21748]
 [197.10405]
 [141.55238]]
1780 Cost: 0.7537116 
Prediction: [[150.49577]
 [185.1944 ]
 [180.2183 ]
 [197.10396]
 [141.5509 ]]
1800 Cost: 0.7524697 
Prediction: [[150.49814]
 [185.19284]
 [180.21912]
 [197.10388]
 [141.54944]]
1820 Cost: 0.75123274 
Prediction: [[150.50049]
 [185.19131]
 [180.21994]
 [197.10379]
 [141.548  ]]
1840 Cost: 0.7499938 
Prediction: [[150.50284]
 [185.18976]
 [180.22073]
 [197.10368]
 [141.54654]]
1860 Cost: 0.74878496 
Prediction: [[150.50517]
 [185.18825]
 [180.22154]
 [197.10362]
 [141.54512]]
1880 Cost: 0.7475549 
Prediction: [[150.50749]
 [185.1867 ]
 [180.22234]
 [197.10349]
 [141.54369

실제 값 : y_data = [[152.], [185.], [180.], [196.], [142.]]

cost 값 0.74로 수렴하고 예측값도 거의 실제값과 유사하게 수렴된다

## Loading data from file

%%writefile 매칭 명령으로 csv 파일 만들기

In [10]:
%%writefile sample1.csv
#EXAM1, EXAM2, EXAM3, FINAL
73, 80, 75, 152
93, 88, 93, 185
89, 91, 90, 180
96, 98, 100, 196
73, 66, 70, 142
53, 46, 55, 101

Overwriting sample1.csv


In [11]:
import numpy as np

xy = np.loadtxt('sample1.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

In [16]:
print(x_data.shape, "\n", x_data, len(x_data))
print(y_data.shape, "\n", y_data)

(6, 3) 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [20]:
n, m = x_data.shape

# make sure the shape and data are OK
X = tf.placeholder(tf.float32, shape=[None, m])  # NONE을 설정해 놓아야 나중에 predict 할때 표본 값을 자유롭게 넣을 수 있다.
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([m, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# model
hypothesis = tf.matmul(X, W) + b

# cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    
    if step % 20 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:", hy_val)

0 Cost: 3212.1716 
Prediction: [[ 95.60658 ]
 [121.32763 ]
 [116.08104 ]
 [127.0178  ]
 [ 93.876305]
 [ 71.359276]]
20 Cost: 8.525262 
Prediction: [[148.755   ]
 [185.18575 ]
 [179.01323 ]
 [195.54694 ]
 [142.58044 ]
 [107.250694]]
40 Cost: 8.442075 
Prediction: [[148.78159]
 [185.17722]
 [179.02617]
 [195.55545]
 [142.56845]
 [107.22846]]
60 Cost: 8.3599615 
Prediction: [[148.80559]
 [185.16586]
 [179.03616]
 [195.56079]
 [142.55432]
 [107.20474]]
80 Cost: 8.278927 
Prediction: [[148.8294 ]
 [185.15456]
 [179.04608]
 [195.56607]
 [142.5403 ]
 [107.18117]]
100 Cost: 8.198906 
Prediction: [[148.85309]
 [185.14333]
 [179.05592]
 [195.57132]
 [142.52637]
 [107.15774]]
120 Cost: 8.1199255 
Prediction: [[148.8766 ]
 [185.13219]
 [179.0657 ]
 [195.5765 ]
 [142.51254]
 [107.13445]]
140 Cost: 8.041961 
Prediction: [[148.89996]
 [185.12111]
 [179.07544]
 [195.58168]
 [142.49883]
 [107.11132]]
160 Cost: 7.964996 
Prediction: [[148.92319]
 [185.11012]
 [179.08511]
 [195.58679]
 [142.4852 ]
 [107.

1540 Cost: 4.4638047 
Prediction: [[150.20488 ]
 [184.5072  ]
 [179.62239 ]
 [195.85544 ]
 [141.75194 ]
 [105.805466]]
1560 Cost: 4.4322724 
Prediction: [[150.2195  ]
 [184.5004  ]
 [179.62856 ]
 [195.85829 ]
 [141.74385 ]
 [105.790634]]
1580 Cost: 4.401133 
Prediction: [[150.234  ]
 [184.49364]
 [179.63469]
 [195.8611 ]
 [141.73584]
 [105.77589]]
1600 Cost: 4.3703694 
Prediction: [[150.24844 ]
 [184.48692 ]
 [179.64082 ]
 [195.86392 ]
 [141.7279  ]
 [105.761246]]
1620 Cost: 4.340003 
Prediction: [[150.26276]
 [184.48024]
 [179.64688]
 [195.86667]
 [141.72   ]
 [105.74668]]
1640 Cost: 4.3099837 
Prediction: [[150.27701]
 [184.47363]
 [179.65291]
 [195.86945]
 [141.7122 ]
 [105.73221]]
1660 Cost: 4.2803655 
Prediction: [[150.29114]
 [184.46706]
 [179.65889]
 [195.87218]
 [141.70442]
 [105.71783]]
1680 Cost: 4.251105 
Prediction: [[150.30519]
 [184.46053]
 [179.66486]
 [195.87488]
 [141.69672]
 [105.70354]]
1700 Cost: 4.222199 
Prediction: [[150.31914]
 [184.45404]
 [179.67076]
 [195.877

In [21]:
y_data

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.],
       [101.]], dtype=float32)

In [22]:
# predict my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

Your score will be  [[189.70505]]


In [23]:
print("Other score will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Other score will be  [[161.39798]
 [176.56564]]


## Queue Runners

그림 : https://mblogthumb-phinf.pstatic.net/MjAxNzAzMjFfMTA4/MDAxNDkwMDg0Njk3MTA5.qfcnDscM6Zf1MXOtNMvzElwm6cvOII0Q9EWBOFj4Me0g.VODO8qxcxAJ-hhkWw6y5VMhVsy_pTFSskp86dlu-sTcg.JPEG.ishkkman/1.jpg?type=w800

* step 1: 파일 리스트 만들기

    + filenames_queue = tf.train.string_input_producer(['data-01-test-score.csv', 'data-02-test-score.csv', 'data-03-test-score.csv', ...], shuffle=False, name='filename_queue')

* step 2: 파일을 읽어올 reader 정의. tf.TextLineReader() 텍스트를 읽어올때 사용
    + reader = tf.TextLineReader()
    + key, value = reader.read(filename_queue)
        
* step 3:
    + record_defaults = [[0.], [0.], [0.]]  # 데이터 타입을 설정하기 위해 디폴트 값을 이렇게 정한다.
    + xy = tf.decode_csv(value, record_defaults=record_defaults)



### Queue Runner 사용

In [27]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(['sample1.csv'], shuffle=False, name='filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values
# decoded result
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# model
hypothesis = tf.matmul(X, W) + b

# cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    
    if step % 20 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Field 0 in record 0 is not a valid float: #EXAM1
	 [[{{node DecodeCSV}}]]


OutOfRangeError: FIFOQueue '_27_batch_3/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[node batch_3 (defined at <ipython-input-27-2f959873d877>:13) ]]

Caused by op 'batch_3', defined at:
  File "/Users/imjunghee/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/imjunghee/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 563, in start
    self.io_loop.start()
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/Users/imjunghee/anaconda3/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/Users/imjunghee/anaconda3/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/Users/imjunghee/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 787, in inner
    self.run()
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2855, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
    return runner(coro)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-2f959873d877>", line 13, in <module>
    train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 1019, in batch
    name=name)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 789, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3645, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Users/imjunghee/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_27_batch_3/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[node batch_3 (defined at <ipython-input-27-2f959873d877>:13) ]]
