### Shape, Rank, Axis

In [1]:
import tensorflow as tf

In [4]:
sess = tf.Session()
t = tf.constant([1, 2, 3, 4])
tf.shape(t).eval(session=sess)

array([4], dtype=int32)

In [5]:
t = tf.constant([[1, 2], [3, 4]])
tf.shape(t).eval(session=sess)

array([2, 2], dtype=int32)

In [6]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
                  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval(session=sess)

array([1, 2, 3, 4], dtype=int32)

### Matmul vs Multiply

In [8]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print("Matrix 1 shape:", matrix1.shape)
print("Matrix 2 shape:", matrix2.shape)
tf.matmul(matrix1, matrix2).eval(session=sess)

Matrix 1 shape: (2, 2)
Matrix 2 shape: (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [9]:
# multiply
(matrix1 * matrix2).eval(session=sess)

array([[1., 2.],
       [6., 8.]], dtype=float32)

### Broadcasting

In [10]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1 * matrix2).eval(session=sess)

array([[3., 6.]], dtype=float32)

In [11]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])  # 차원추가함
(matrix1 + matrix2).eval(session=sess)

array([[4., 6.]], dtype=float32)

In [12]:
# shape이 달라도 더한 결과를 반환한다. 따라서 주의 필요!!
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])
(matrix1 + matrix2).eval(session=sess)

array([[4., 5.],
       [5., 6.]], dtype=float32)

### Reduce mean

In [13]:
tf.reduce_mean([1, 2], axis=0).eval(session=sess)

1

In [14]:
x = [[1., 2.], [3., 4.]]

tf.reduce_mean(x).eval(session=sess)

2.5

In [15]:
tf.reduce_mean(x, axis=0).eval(session=sess)

array([2., 3.], dtype=float32)

In [16]:
tf.reduce_mean(x, axis=1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

In [17]:
tf.reduce_mean(x, axis=-1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

### Reduce sum

In [18]:
tf.reduce_sum(x).eval(session=sess)

10.0

In [19]:
tf.reduce_sum(x, axis=0).eval(session=sess)

array([4., 6.], dtype=float32)

In [20]:
tf.reduce_sum(x, axis=1).eval(session=sess)

array([3., 7.], dtype=float32)

In [21]:
tf.reduce_sum(x, axis=-1).eval(session=sess)

array([3., 7.], dtype=float32)

In [22]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval(session=sess)

5.0

### Argmax

In [23]:
x = [[0, 1, 2], 
     [2, 1, 0]]

tf.argmax(x, axis=0).eval(session=sess)

array([1, 0, 0])

In [24]:
tf.argmax(x, axis=1).eval(session=sess)

array([2, 0])

In [25]:
tf.argmax(x, axis=-1).eval(session=sess)

array([2, 0])

### Reshape

In [26]:
import numpy as np

In [27]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]], 
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [28]:
tf.reshape(t, shape=[-1, 3]).eval(session=sess)  # 차원 축소 4 x 3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
tf.reshape(t, shape=[-1, 1, 3]).eval(session=sess) # 4 x 1 x 3

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

### Reshape(squeeze, expand)

In [30]:
tf.squeeze([[0], [1], [2]]).eval(session=sess) # 1차원으로 풀어준다

array([0, 1, 2], dtype=int32)

In [31]:
tf.expand_dims([0, 1, 2], axis=1).eval(session=sess)  # 차원 확대

array([[0],
       [1],
       [2]], dtype=int32)

In [33]:
tf.expand_dims([0, 1, 2], axis=0).eval(session=sess)  # 차원 확대

array([[0, 1, 2]], dtype=int32)

### One hot

In [34]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval(session=sess)

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [35]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval(session=sess)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

### Casting

In [36]:
tf.cast([1.0, 2.2, 3.3, 4.9], tf.int32).eval(session=sess)  # 정수로 변환해 줌

array([1, 2, 3, 4], dtype=int32)

In [37]:
tf.cast([True, False, 1==0, 0==1], tf.int32).eval(session=sess)  # true 1로 false 0으로 변환

array([1, 0, 0, 0], dtype=int32)

### Stack

In [38]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# pack along first dim.
tf.stack([x, y, z]).eval(session=sess)

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [39]:
tf.stack([x, y, z], axis=1).eval(session=sess)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

### Zip

In [40]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [41]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


### Ones and Zeros like

In [42]:
x = [[0, 1, 2], 
     [2, 1, 0]]

tf.ones_like(x).eval(session=sess)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [43]:
tf.zeros_like(x).eval(session=sess)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)